In [1]:
import numpy as np

#### Define the function `my_generator`
Accepts numPy arrays and iterates two records at a time in the array

In [2]:
def my_generator(my_array):
    i = 0
    while True:
        # output two elements at a time
        yield my_array[i:i+2, :]
        i += 1
        

In [3]:
# Create an array to test the function above
test_array = np.array([[10.0, 2.0],
                       [15, 6.0],
                       [3.2, -1.5],
                       [-3, -2]], np.float32)

In [4]:
output = my_generator(test_array)

In [5]:
next(output) #1

array([[10.,  2.],
       [15.,  6.]], dtype=float32)

In [6]:
next(output) #2

array([[15. ,  6. ],
       [ 3.2, -1.5]], dtype=float32)

In [7]:
next(output) #3

array([[ 3.2, -1.5],
       [-3. , -2. ]], dtype=float32)

In [8]:
next(output) #4

array([[-3., -2.]], dtype=float32)

In [9]:
next(output) #5 Now the function finished the iterations and we get an empty array

array([], shape=(0, 2), dtype=float32)

This function streams two records in a NumPy array each time it is run (Instead we can use a loop to also iterate the through the function?).
The use of `yield`statement instead of `return`: unlike `return`, `yield`produces a sequence of values whitout storing the entire sequence in the Python runtime memory, `yield`continues to produce a sequence each time we invoke the `next` function until the end of array is reached.

In [10]:
### for i in range(0, 4):
###   print(next(output))
### only working when the function is not already run 4 times. that's why is printing four empty arrays

👁️ This array is held in Python runtime memory. Let's see how to iterate through a dataset stored in a local file